//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Shifts.Integration.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Shifts.Integration.Configuration.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration has been successfully deleted from the system..
        /// </summary>
        public static string ConfigurationEntityDeletionSuccessContent {
            get {
                return ResourceManager.GetString("ConfigurationEntityDeletionSuccessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration has been successfully saved! Click on the Register link to register the Kronos Workforce Integration with Microsoft Graph..
        /// </summary>
        public static string ConfigurationSavedSuccessNextStepsText {
            get {
                return ResourceManager.GetString("ConfigurationSavedSuccessNextStepsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        public static string DownloadTemplateoUserMappingButtonText {
            get {
                return ResourceManager.GetString("DownloadTemplateoUserMappingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorNotificationHeaderText {
            get {
                return ResourceManager.GetString("ErrorNotificationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportUserToUserMappingButtonText {
            get {
                return ResourceManager.GetString("ExportUserToUserMappingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities has been successfully synced!.
        /// </summary>
        public static string FirstTimeSyncSuccessText {
            get {
                return ResourceManager.GetString("FirstTimeSyncSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the form below in order to setup your instance of Kronos WFC 8 to work with Shifts. This is a one-time setup. It is required that you provide the correct SuperUser credentials for Kronos. Once all information has been entered, click on Submit..
        /// </summary>
        public static string HomePageInstructionText {
            get {
                return ResourceManager.GetString("HomePageInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Mapping.
        /// </summary>
        public static string ImportTeamToDepartmentMappingButtonText {
            get {
                return ResourceManager.GetString("ImportTeamToDepartmentMappingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Mapping.
        /// </summary>
        public static string ImportUserToUserMappingButtonText {
            get {
                return ResourceManager.GetString("ImportUserToUserMappingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login with the provided credentials for Kronos. Please correct and try again!.
        /// </summary>
        public static string KronosErrorContentText {
            get {
                return ResourceManager.GetString("KronosErrorContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kronos_shift_usermapping.xlsx.
        /// </summary>
        public static string KronosShiftUserMappingXML {
            get {
                return ResourceManager.GetString("KronosShiftUserMappingXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string NoOfColumnsInExcel {
            get {
                return ResourceManager.GetString("NoOfColumnsInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Workforce Integration ID to delete. Please make sure that you have an ID in order to delete it..
        /// </summary>
        public static string NoWfiIdExistsContentText {
            get {
                return ResourceManager.GetString("NoWfiIdExistsContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveShiftsTeamKronosDepartmentMappingAsync.
        /// </summary>
        public static string SaveShiftsTeamKronosDepartmentMappingAsync {
            get {
                return ResourceManager.GetString("SaveShiftsTeamKronosDepartmentMappingAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify workforce integration, user mapping, team department mapping are done..
        /// </summary>
        public static string SetUpNotDoneMessage {
            get {
                return ResourceManager.GetString("SetUpNotDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sync has initiated successfully..
        /// </summary>
        public static string SetUpSuccessfulMessage {
            get {
                return ResourceManager.GetString("SetUpSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
        /// </summary>
        public static string SpreadsheetContentType {
            get {
                return ResourceManager.GetString("SpreadsheetContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessNotificationHeaderText {
            get {
                return ResourceManager.GetString("SuccessNotificationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sync could not be initiated..
        /// </summary>
        public static string SyncKronosToShiftsError {
            get {
                return ResourceManager.GetString("SyncKronosToShiftsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to properly map the team &amp; department between Shifts and Kronos, please follow the steps below:.
        /// </summary>
        public static string TeamDepartmentMappingPageInstructionText {
            get {
                return ResourceManager.GetString("TeamDepartmentMappingPageInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the export button - this exports team &amp; department details in both Shifts and Kronos, and will download a file to your local downloads folder..
        /// </summary>
        public static string TeamDepartmentMappingPageInstructionTextStep1 {
            get {
                return ResourceManager.GetString("TeamDepartmentMappingPageInstructionTextStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the download template button - this will generate an empty Excel file that contains the following columns: (WorkforceIntegrationId, KronosOrgJobPath, ShiftTeamId, ShiftTeamName, ShiftSchedulingGroupId, ShiftSchedulingGroupName).
        /// </summary>
        public static string TeamDepartmentMappingPageInstructionTextStep2 {
            get {
                return ResourceManager.GetString("TeamDepartmentMappingPageInstructionTextStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the team &amp; department have been mapped in the template file, click on the import mapping button, select the template file that you recently modified and upload..
        /// </summary>
        public static string TeamDepartmentMappingPageInstructionTextStep3 {
            get {
                return ResourceManager.GetString("TeamDepartmentMappingPageInstructionTextStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to populate this template file with the team &amp; department that are going to be mapped. Select respective team &amp; department details from the exported excel..
        /// </summary>
        public static string TeamDepartmentMappingPageInstructionTextSubStep2 {
            get {
                return ResourceManager.GetString("TeamDepartmentMappingPageInstructionTextSubStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the teamDetailsResponse.
        /// </summary>
        public static string TeamDetailsResponseNullOrEmpty {
            get {
                return ResourceManager.GetString("TeamDetailsResponseNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected team?.
        /// </summary>
        public static string TeamMappingDeletePopUpMessage {
            get {
                return ResourceManager.GetString("TeamMappingDeletePopUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teams_department_usermapping.xlsx.
        /// </summary>
        public static string TeamsDepartmentMappingXML {
            get {
                return ResourceManager.GetString("TeamsDepartmentMappingXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an auto populated value representing your O365 Tenant..
        /// </summary>
        public static string TenantIdToolTipHoverMessage {
            get {
                return ResourceManager.GetString("TenantIdToolTipHoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cached token cache is for a different user! Make sure the token cache factory is registered as Scoped!.
        /// </summary>
        public static string TokenCacheReuseExceptionMessage {
            get {
                return ResourceManager.GetString("TokenCacheReuseExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully!.
        /// </summary>
        public static string UpdateNotificationHeaderText {
            get {
                return ResourceManager.GetString("UpdateNotificationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the user mapping?.
        /// </summary>
        public static string UserMappingDeletePopUpMessage {
            get {
                return ResourceManager.GetString("UserMappingDeletePopUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to properly map the users between AAD and Kronos, please follow the steps below:.
        /// </summary>
        public static string UserToUserMappingPageInstructionText {
            get {
                return ResourceManager.GetString("UserToUserMappingPageInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the export button - this exports user details in both AAD and Kronos, and will download a file to your local downloads folder..
        /// </summary>
        public static string UserToUserMappingPageInstructionTextStep1 {
            get {
                return ResourceManager.GetString("UserToUserMappingPageInstructionTextStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the download template button - this will generate an empty Excel file that contains the following columns: (KronosOrgJobPath, KronosPersonNumber, KronosUserName, ShiftAADObjectId, ShiftUserDisplayName, ShiftUserPrincipalName).
        /// </summary>
        public static string UserToUserMappingPageInstructionTextStep2 {
            get {
                return ResourceManager.GetString("UserToUserMappingPageInstructionTextStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the users have been mapped in the template file, click on the import mapping button, select the template file that you recently modified and upload..
        /// </summary>
        public static string UserToUserMappingPageInstructionTextStep3 {
            get {
                return ResourceManager.GetString("UserToUserMappingPageInstructionTextStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to populate this template file with the users that are going to be mapped. Select respective user details from the exported excel..
        /// </summary>
        public static string UserToUserMappingPageInstructionTextSubStep2 {
            get {
                return ResourceManager.GetString("UserToUserMappingPageInstructionTextSubStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workforce Integration {0} is already registered..
        /// </summary>
        public static string WFIAlreadyRegHeaderText {
            get {
                return ResourceManager.GetString("WFIAlreadyRegHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure to delete all the mapped Team/Department before deleting Workforce Integration {0}..
        /// </summary>
        public static string WFIDeleteFailedDueToTeamDeptMappingText {
            get {
                return ResourceManager.GetString("WFIDeleteFailedDueToTeamDeptMappingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected workforce integration?.
        /// </summary>
        public static string WFIDeletePopUpMessage {
            get {
                return ResourceManager.GetString("WFIDeletePopUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workforce integration {0} failed to delete..
        /// </summary>
        public static string WfiDeletionFailed {
            get {
                return ResourceManager.GetString("WfiDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workforce integration: {0} has been deleted successfully!.
        /// </summary>
        public static string WfiDeletionSuccessText {
            get {
                return ResourceManager.GetString("WfiDeletionSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workforce Integration Registration.
        /// </summary>
        public static string WFIGeneralHeaderText {
            get {
                return ResourceManager.GetString("WFIGeneralHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been failed to register!.
        /// </summary>
        public static string WFIRegFailedContentText {
            get {
                return ResourceManager.GetString("WFIRegFailedContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workforce Integration Failed to Register!.
        /// </summary>
        public static string WFIRegFailedHeaderText {
            get {
                return ResourceManager.GetString("WFIRegFailedHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully registered!.
        /// </summary>
        public static string WFIRegSuccessContentText {
            get {
                return ResourceManager.GetString("WFIRegSuccessContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workforce Integration Registration Success.
        /// </summary>
        public static string WFIRegSuccessHeaderText {
            get {
                return ResourceManager.GetString("WFIRegSuccessHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Kronos WFC API Endpoint..
        /// </summary>
        public static string WfmApiEndpointToolTipHoverMessage {
            get {
                return ResourceManager.GetString("WfmApiEndpointToolTipHoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of your Workforce Management provider. For example, if you plan to register Kronos WFC, enter KronosWFC. Once you are satisfied, fill in the other details and click on Register..
        /// </summary>
        public static string WfmProviderToolTipHoverMessage {
            get {
                return ResourceManager.GetString("WfmProviderToolTipHoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Kronos Super Username..
        /// </summary>
        public static string WfmSuperUsernameToolTipHoverMessage {
            get {
                return ResourceManager.GetString("WfmSuperUsernameToolTipHoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Kronos Super User Password..
        /// </summary>
        public static string WfmSuperUserPasswordToolTipHoverMessage {
            get {
                return ResourceManager.GetString("WfmSuperUserPasswordToolTipHoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workforce Integration is not registered. Please register workforce integration..
        /// </summary>
        public static string WorkforceIntegrationNotRegister {
            get {
                return ResourceManager.GetString("WorkforceIntegrationNotRegister", resourceCulture);
            }
        }
    }
}
