//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Shifts.Integration.BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessLogicResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessLogicResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Shifts.Integration.BusinessLogic.BusinessLogicResource", typeof(BusinessLogicResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddWorkForceIntegrationToSchedule.
        /// </summary>
        public static string AddWorkForceIntegrationToSchedule {
            get {
                return ResourceManager.GetString("AddWorkForceIntegrationToSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteWorkforceIntegrationAsync.
        /// </summary>
        public static string DeleteWorkforceIntegrationAsync {
            get {
                return ResourceManager.GetString("DeleteWorkforceIntegrationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnsureInitializedAsync.
        /// </summary>
        public static string EnsureInitializedAsync {
            get {
                return ResourceManager.GetString("EnsureInitializedAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FetchShiftTeamDetailsAsync.
        /// </summary>
        public static string FetchShiftTeamDetailsAsync {
            get {
                return ResourceManager.GetString("FetchShiftTeamDetailsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FetchShiftUserDetailsAsync.
        /// </summary>
        public static string FetchShiftUserDetailsAsync {
            get {
                return ResourceManager.GetString("FetchShiftUserDetailsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetKronosReqAsync.
        /// </summary>
        public static string GetKronosReqAsync {
            get {
                return ResourceManager.GetString("GetKronosReqAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetShiftEntityMappingByRowKeyAsync.
        /// </summary>
        public static string GetShiftEntityMappingByRowKeyAsync {
            get {
                return ResourceManager.GetString("GetShiftEntityMappingByRowKeyAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializeAsync.
        /// </summary>
        public static string InitializeAsync {
            get {
                return ResourceManager.GetString("InitializeAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterWorkforceIntegrationAsync.
        /// </summary>
        public static string RegisterWorkforceIntegrationAsync {
            get {
                return ResourceManager.GetString("RegisterWorkforceIntegrationAsync", resourceCulture);
            }
        }
    }
}
