//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Shifts.Integration.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Shifts.Integration.API.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddSwapShiftApprovalAsync.
        /// </summary>
        public static string AddSwapShiftApprovalAsync {
            get {
                return ResourceManager.GetString("AddSwapShiftApprovalAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApproveOrDeclineSwapShiftRequestToKronosAsync.
        /// </summary>
        public static string ApproveOrDeclineSwapShiftRequestToKronosAsync {
            get {
                return ResourceManager.GetString("ApproveOrDeclineSwapShiftRequestToKronosAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        public static string Cancle {
            get {
                return ResourceManager.GetString("Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckRequestStatus.
        /// </summary>
        public static string CheckRequestStatus {
            get {
                return ResourceManager.GetString("CheckRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateEntryOpenShiftsEntityMapping.
        /// </summary>
        public static string CreateEntryOpenShiftsEntityMapping {
            get {
                return ResourceManager.GetString("CreateEntryOpenShiftsEntityMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateEntryOpenShiftsEntityMappingAsync.
        /// </summary>
        public static string CreateEntryOpenShiftsEntityMappingAsync {
            get {
                return ResourceManager.GetString("CreateEntryOpenShiftsEntityMappingAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewOpenShiftMappingEntity.
        /// </summary>
        public static string CreateNewOpenShiftMappingEntity {
            get {
                return ResourceManager.GetString("CreateNewOpenShiftMappingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeclineSwapShiftRequestAsync.
        /// </summary>
        public static string DeclineSwapShiftRequestAsync {
            get {
                return ResourceManager.GetString("DeclineSwapShiftRequestAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteOrphanDataOpenShiftsEntityMapping.
        /// </summary>
        public static string DeleteOrphanDataOpenShiftsEntityMapping {
            get {
                return ResourceManager.GetString("DeleteOrphanDataOpenShiftsEntityMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteOrphanDataOpenShiftsEntityMappingAsync.
        /// </summary>
        public static string DeleteOrphanDataOpenShiftsEntityMappingAsync {
            get {
                return ResourceManager.GetString("DeleteOrphanDataOpenShiftsEntityMappingAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string DraftOpenShiftRequestSegmentTypeName {
            get {
                return ResourceManager.GetString("DraftOpenShiftRequestSegmentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full_day.
        /// </summary>
        public static string DurationInFullDay {
            get {
                return ResourceManager.GetString("DurationInFullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second_half_day.
        /// </summary>
        public static string DurationInHalfDay {
            get {
                return ResourceManager.GetString("DurationInHalfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string DurationInHour {
            get {
                return ResourceManager.GetString("DurationInHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the entity with the RowKey: {0}.
        /// </summary>
        public static string EntityNotFoundWithRowKey {
            get {
                return ResourceManager.GetString("EntityNotFoundWithRowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstablishHandshake.
        /// </summary>
        public static string EstablishHandshake {
            get {
                return ResourceManager.GetString("EstablishHandshake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GeneralErrorCode {
            get {
                return ResourceManager.GetString("GeneralErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, you may need to reissue your request again at a later time..
        /// </summary>
        public static string GeneralErrorMessageText {
            get {
                return ResourceManager.GetString("GeneralErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Data cannot be retrieved at this time..
        /// </summary>
        public static string GenericNotAbleToRetrieveDataMessage {
            get {
                return ResourceManager.GetString("GenericNotAbleToRetrieveDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetOpenShiftResultsByOrgJobPathInBatch.
        /// </summary>
        public static string GetOpenShiftResultsByOrgJobPathInBatch {
            get {
                return ResourceManager.GetString("GetOpenShiftResultsByOrgJobPathInBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetOpenShiftResultsByOrgJobPathInBatchAsync.
        /// </summary>
        public static string GetOpenShiftResultsByOrgJobPathInBatchAsync {
            get {
                return ResourceManager.GetString("GetOpenShiftResultsByOrgJobPathInBatchAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetShifts.
        /// </summary>
        public static string GetShifts {
            get {
                return ResourceManager.GetString("GetShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTimeOffs.
        /// </summary>
        public static string GetTimeOffs {
            get {
                return ResourceManager.GetString("GetTimeOffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncomingOpenShiftRequest.
        /// </summary>
        public static string IncomingOpenShiftRequest {
            get {
                return ResourceManager.GetString("IncomingOpenShiftRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the argument passed..
        /// </summary>
        public static string IncorrectArgumentType {
            get {
                return ResourceManager.GetString("IncorrectArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred which may cause the open shift request to be declined..
        /// </summary>
        public static string InternalErrorCodeMessageText {
            get {
                return ResourceManager.GetString("InternalErrorCodeMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalError.
        /// </summary>
        public static string InternalErrorCodeText {
            get {
                return ResourceManager.GetString("InternalErrorCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Occurred.
        /// </summary>
        public static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login Kronos..
        /// </summary>
        public static string InvalidKronosCredentials {
            get {
                return ResourceManager.GetString("InvalidKronosCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Shift is not in pending with manager state. Swap Shift Request Id: {0} .
        /// </summary>
        public static string InvalidSwapShiftState {
            get {
                return ResourceManager.GetString("InvalidSwapShiftState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch shifts access token. Please try to relogin..
        /// </summary>
        public static string IssueShiftsAccessToken {
            get {
                return ResourceManager.GetString("IssueShiftsAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KronosErrorStatus.
        /// </summary>
        public static string KronosErrorStatus {
            get {
                return ResourceManager.GetString("KronosErrorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating to submitted status..
        /// </summary>
        public static string KronosOpenShiftStatusUpdateToSubmittedMessage {
            get {
                return ResourceManager.GetString("KronosOpenShiftStatusUpdateToSubmittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kronos URL not present..
        /// </summary>
        public static string KronosURLNotPresent {
            get {
                return ResourceManager.GetString("KronosURLNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenShiftRequestError.
        /// </summary>
        public static string KronosWFCOpenShiftRequestErrorCode {
            get {
                return ResourceManager.GetString("KronosWFCOpenShiftRequestErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapPayCodeTimeOffReasonsAsync.
        /// </summary>
        public static string MapPayCodeTimeOffReasonsAsync {
            get {
                return ResourceManager.GetString("MapPayCodeTimeOffReasonsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthPartitionKeyStatus.
        /// </summary>
        public static string MonthPartitionKeyStatus {
            get {
                return ResourceManager.GetString("MonthPartitionKeyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests present in pending state..
        /// </summary>
        public static string NoSwapReqPending {
            get {
                return ResourceManager.GetString("NoSwapReqPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month partitions are null. Please verify your data in Kronos accordingly.
        /// </summary>
        public static string NullMonthPartitionsMessage {
            get {
                return ResourceManager.GetString("NullMonthPartitionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenShiftNotFound.
        /// </summary>
        public static string OpenShiftNotFoundCode {
            get {
                return ResourceManager.GetString("OpenShiftNotFoundCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The open shift from MS Graph - {0} is not found..
        /// </summary>
        public static string OpenShiftNotFoundMessage {
            get {
                return ResourceManager.GetString("OpenShiftNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string OpenShiftRequestApprovalMessage {
            get {
                return ResourceManager.GetString("OpenShiftRequestApprovalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string OpenShiftRequestDeclinedMessage {
            get {
                return ResourceManager.GetString("OpenShiftRequestDeclinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passthrough header does not exist in request..
        /// </summary>
        public static string PassthroughHeaderNotPresent {
            get {
                return ResourceManager.GetString("PassthroughHeaderNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound request is coming from correct WFIntegration.
        /// </summary>
        public static string PassthroughHeaderWFIIDMatched {
            get {
                return ResourceManager.GetString("PassthroughHeaderWFIIDMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workforce Integration is incorrect..
        /// </summary>
        public static string PassthroughHeaderWFIIDMismatch {
            get {
                return ResourceManager.GetString("PassthroughHeaderWFIIDMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a payload received, but does not suffice any of the conditions for processing..
        /// </summary>
        public static string PayloadReceivedDoesNotMeetConditions {
            get {
                return ResourceManager.GetString("PayloadReceivedDoesNotMeetConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager action is not allowed from Shifts..
        /// </summary>
        public static string PreventManageActionFromShifts {
            get {
                return ResourceManager.GetString("PreventManageActionFromShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessKronosToShiftsShiftsAsync.
        /// </summary>
        public static string ProcessKronosToShiftsShiftsAsync {
            get {
                return ResourceManager.GetString("ProcessKronosToShiftsShiftsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessOpenShiftsAsync.
        /// </summary>
        public static string ProcessOpenShiftsAsync {
            get {
                return ResourceManager.GetString("ProcessOpenShiftsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessOpenShiftsRequests.
        /// </summary>
        public static string ProcessOpenShiftsRequests {
            get {
                return ResourceManager.GetString("ProcessOpenShiftsRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessOutboundOpenShiftRequestAsync.
        /// </summary>
        public static string ProcessOutboundOpenShiftRequestAsync {
            get {
                return ResourceManager.GetString("ProcessOutboundOpenShiftRequestAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessShiftsAsync.
        /// </summary>
        public static string ProcessShiftsAsync {
            get {
                return ResourceManager.GetString("ProcessShiftsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessSwapShiftsAsync.
        /// </summary>
        public static string ProcessSwapShiftsAsync {
            get {
                return ResourceManager.GetString("ProcessSwapShiftsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessTimeOffRequestsAsync.
        /// </summary>
        public static string ProcessTimeOffRequestsAsync {
            get {
                return ResourceManager.GetString("ProcessTimeOffRequestsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessTimeOffsAsync.
        /// </summary>
        public static string ProcessTimeOffsAsync {
            get {
                return ResourceManager.GetString("ProcessTimeOffsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient shift not found.
        /// </summary>
        public static string RecipientShiftNotFound {
            get {
                return ResourceManager.GetString("RecipientShiftNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request is coming in from Shifts, but does not meet the necessary criteria for further processing: {0}..
        /// </summary>
        public static string RequestFromShiftsNotQualifiedToProcess {
            get {
                return ResourceManager.GetString("RequestFromShiftsNotQualifiedToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender shift not found.
        /// </summary>
        public static string SenderShiftNotFound {
            get {
                return ResourceManager.GetString("SenderShiftNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetUpNotDone.
        /// </summary>
        public static string SetUpNotDoneCode {
            get {
                return ResourceManager.GetString("SetUpNotDoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify workforce integration, user mapping, team department mapping are done and sync start date and end date are in &quot;M/dd/yyyy&quot; format where start date &lt; end date..
        /// </summary>
        public static string SetUpNotDoneMessage {
            get {
                return ResourceManager.GetString("SetUpNotDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup done: {0}.
        /// </summary>
        public static string SetupStatusMessage {
            get {
                return ResourceManager.GetString("SetupStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No swap shifts found to process.
        /// </summary>
        public static string ShiftsNotFoundtoSwap {
            get {
                return ResourceManager.GetString("ShiftsNotFoundtoSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitOpenShiftRequestToKronosAsync.
        /// </summary>
        public static string SubmitOpenShiftRequestToKronosAsync {
            get {
                return ResourceManager.GetString("SubmitOpenShiftRequestToKronosAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitSwapShiftRequestToKronosAsync.
        /// </summary>
        public static string SubmitSwapShiftRequestToKronosAsync {
            get {
                return ResourceManager.GetString("SubmitSwapShiftRequestToKronosAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncApprovedOrDeclinedOpenShiftRequests.
        /// </summary>
        public static string SyncApprovedOrDeclinedOpenShiftRequests {
            get {
                return ResourceManager.GetString("SyncApprovedOrDeclinedOpenShiftRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncApprovedOrDeclinedOpenShiftRequestsAsync.
        /// </summary>
        public static string SyncApprovedOrDeclinedOpenShiftRequestsAsync {
            get {
                return ResourceManager.GetString("SyncApprovedOrDeclinedOpenShiftRequestsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while syncing the shifts..
        /// </summary>
        public static string SyncedFailed {
            get {
                return ResourceManager.GetString("SyncedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncOpenShiftsFromKronos.
        /// </summary>
        public static string SyncOpenShiftsFromKronos {
            get {
                return ResourceManager.GetString("SyncOpenShiftsFromKronos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncShiftsFromKronos.
        /// </summary>
        public static string SyncShiftsFromKronos {
            get {
                return ResourceManager.GetString("SyncShiftsFromKronos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncSwapShiftsFromKronos.
        /// </summary>
        public static string SyncSwapShiftsFromKronos {
            get {
                return ResourceManager.GetString("SyncSwapShiftsFromKronos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTimeOffRequestsFromShiftsToKronos.
        /// </summary>
        public static string SyncTimeOffRequestsFromShiftsToKronos {
            get {
                return ResourceManager.GetString("SyncTimeOffRequestsFromShiftsToKronos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is declined by system.
        /// </summary>
        public static string SystemDeclined {
            get {
                return ResourceManager.GetString("SystemDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team-department details cannot be found. Check the Team-Department mapping and try again..
        /// </summary>
        public static string TeamDepartmentDetailsNotFoundMessage {
            get {
                return ResourceManager.GetString("TeamDepartmentDetailsNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find that time off reason..
        /// </summary>
        public static string TimeOffReasonNotFound {
            get {
                return ResourceManager.GetString("TimeOffReasonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to approve the time off request..
        /// </summary>
        public static string TimeOffRequestApproveFailed {
            get {
                return ResourceManager.GetString("TimeOffRequestApproveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the time off request..
        /// </summary>
        public static string TimeOffRequestCreationFailed {
            get {
                return ResourceManager.GetString("TimeOffRequestCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decline the time off request..
        /// </summary>
        public static string TimeOffRequestDeclineFailed {
            get {
                return ResourceManager.GetString("TimeOffRequestDeclineFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is not present with the current request..
        /// </summary>
        public static string TokenNotPresentWithCurrentRequest {
            get {
                return ResourceManager.GetString("TokenNotPresentWithCurrentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token required for this API call could be coming from an invalid source..
        /// </summary>
        public static string TokenOriginatingFromInvalidSource {
            get {
                return ResourceManager.GetString("TokenOriginatingFromInvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not mapped in Workforce Integration..
        /// </summary>
        public static string UserMappingNotFound {
            get {
                return ResourceManager.GetString("UserMappingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team does not exist for user.
        /// </summary>
        public static string UserTeamNotExists {
            get {
                return ResourceManager.GetString("UserTeamNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the admin ID for workforce integration..
        /// </summary>
        public static string WorkforceIntegrationAdminNotFound {
            get {
                return ResourceManager.GetString("WorkforceIntegrationAdminNotFound", resourceCulture);
            }
        }
    }
}
